name: Run Tests
description: 'Runs phpunit tests uisng the stubs submodule' 

runs: 
  using: "composite"
  steps:
    - name: Setup PHP Unit 8.2
      uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
    - run: wget https://phar.phpunit.de/phpunit-10.1.1.phar
      shell: bash
    - run: php phpunit-10.1.1.phar tests --configuration tests/phpunit.xml 
      shell: bash   